// Code generated by go generate; DO NOT EDIT.
//go:build fusion
package tikvrpc

// we don't set the linker flags here because caller may use a mock implementation.

// #cgo CFLAGS: -I/usr/local/include -I${SRCDIR}/../../libtikv
// #include "libtikv.h"
// #cgo nocallback tikv_client_async_api_send_request
// #cgo nocallback tikv_client_drop_response
import "C"
import (
 "context"
 "encoding/binary"
 "fmt"
 "math"
 "runtime"
 "time"
 "unsafe"

 "github.com/pingcap/errors"
 "github.com/tikv/client-go/v2/metrics"
 "github.com/pingcap/kvproto/pkg/kvrpcpb"
 "github.com/pingcap/kvproto/pkg/coprocessor"
)

type respOrErr struct {
 resp *Response
 err  error
 ts   int64 // ts record the timestamp when notify
}

func CallFFIWithEventFD(ctx context.Context, req *Request) (*Response, error) {
 observer := metrics.TiKVFFIMicroSecHistogramVec.WithLabelValues(req.Type.String())
 now := time.Now()
 defer func() {
     observer.Observe(float64(time.Since(now).Microseconds()))
 }()
 switch req.Type {
 case CmdGet:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.Get().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(KvGet)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.GetResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.GetResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdScan:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.Scan().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(KvScan)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.ScanResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.ScanResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdPrewrite:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.Prewrite().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(KvPrewrite)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.PrewriteResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.PrewriteResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdPessimisticLock:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.PessimisticLock().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(KvPessimisticLock)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.PessimisticLockResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.PessimisticLockResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdPessimisticRollback:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.PessimisticRollback().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(KVPessimisticRollback)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.PessimisticRollbackResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.PessimisticRollbackResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdCommit:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.Commit().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(KvCommit)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.CommitResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.CommitResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdCleanup:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.Cleanup().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(KvCleanup)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.CleanupResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.CleanupResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdBatchGet:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.BatchGet().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(KvBatchGet)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.BatchGetResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.BatchGetResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdBatchRollback:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.BatchRollback().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(KvBatchRollback)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.BatchRollbackResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.BatchRollbackResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdScanLock:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.ScanLock().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(KvScanLock)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.ScanLockResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.ScanLockResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdResolveLock:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.ResolveLock().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(KvResolveLock)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.ResolveLockResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.ResolveLockResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdDeleteRange:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.DeleteRange().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(KvDeleteRange)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.DeleteRangeResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.DeleteRangeResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdRawGet:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawGet().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(RawGet)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.RawGetResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.RawGetResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdRawBatchGet:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawBatchGet().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(RawBatchGet)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.RawBatchGetResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.RawBatchGetResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdRawPut:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawPut().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(RawPut)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.RawPutResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.RawPutResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdRawBatchPut:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawBatchPut().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(RawBatchPut)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.RawBatchPutResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.RawBatchPutResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdRawDelete:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawDelete().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(RawDelete)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.RawDeleteResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.RawDeleteResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdRawBatchDelete:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawBatchDelete().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(RawBatchDelete)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.RawBatchDeleteResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.RawBatchDeleteResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdRawDeleteRange:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawDeleteRange().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(RawDeleteRange)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.RawDeleteRangeResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.RawDeleteRangeResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdRawScan:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawScan().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(RawScan)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.RawScanResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.RawScanResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdGetKeyTTL:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawGetKeyTTL().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(RawGetKeyTTL)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.RawGetKeyTTLResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.RawGetKeyTTLResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdRawCompareAndSwap:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawCompareAndSwap().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(RawCompareAndSwap)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.RawCASResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.RawCASResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdRawChecksum:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawChecksum().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(RawChecksum)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.RawChecksumResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.RawChecksumResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdCop:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.Cop().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(Coprocessor)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  // Some types of responses are zero copy unmarshal.
  // But the original bytes passed from Rust are on Rust's execution stack and will destroy when the function returns.
  // To avoid dangling pointers, the original bytes need to be copied here.
  // Currently known zero copy structures:
  //   - github.com/pingcap/kvproto/pkg/sharedbytes.SharedBytes
  tmp := make([]byte, uint64(respLen))
  copy(tmp, respBytes)
  respBytes = tmp
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &coprocessor.Response{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal coprocessor.Response")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdMvccGetByStartTs:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.MvccGetByStartTs().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(MvccGetByStartTs)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.MvccGetByStartTsResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.MvccGetByStartTsResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdCheckTxnStatus:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.CheckTxnStatus().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(KvCheckTxnStatus)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.CheckTxnStatusResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.CheckTxnStatusResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdCheckSecondaryLocks:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.CheckSecondaryLocks().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(KvCheckSecondaryLocks)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.CheckSecondaryLocksResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.CheckSecondaryLocksResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdTxnHeartBeat:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.TxnHeartBeat().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(KvTxnHeartBeat)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.TxnHeartBeatResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.TxnHeartBeatResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdFlush:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.Flush().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(KvFlush)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.FlushResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.FlushResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdBufferBatchGet:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.BufferBatchGet().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(KvBufferBatchGet)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.BufferBatchGetResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.BufferBatchGetResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 case CmdBroadcastTxnStatus:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.BroadcastTxnStatus().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  c, err := getEventFDFile()
  if err != nil {
   c = createEventFDFile()
   if c.err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer putEventFDFile(c)
  m := (C.uint64_t)(BroadcastTxnStatus)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(c.fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(c)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &kvrpcpb.BroadcastTxnStatusResponse{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, errors.Annotate(err, "failed to unmarshal kvrpcpb.BroadcastTxnStatusResponse")
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_ERROR_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
 default:
  return nil, errors.Errorf("invalid request type: %v", req.Type)
 }
}

func CallFFIWithChannel(ctx context.Context, req *Request) (*Response, error) {
 observer := metrics.TiKVFFIMicroSecHistogramVec.WithLabelValues(req.Type.String())
 now := time.Now()
 defer func() {
     observer.Observe(float64(time.Since(now).Microseconds()))
 }()
 ch := make(chan respOrErr, 1)
 chPtr := (*C.uchar)(unsafe.Pointer(&ch))
 switch req.Type {
 case CmdGet:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.Get().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(KvGet)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdScan:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.Scan().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(KvScan)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdPrewrite:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.Prewrite().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(KvPrewrite)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdPessimisticLock:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.PessimisticLock().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(KvPessimisticLock)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdPessimisticRollback:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.PessimisticRollback().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(KVPessimisticRollback)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdCommit:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.Commit().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(KvCommit)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdCleanup:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.Cleanup().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(KvCleanup)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdBatchGet:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.BatchGet().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(KvBatchGet)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdBatchRollback:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.BatchRollback().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(KvBatchRollback)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdScanLock:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.ScanLock().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(KvScanLock)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdResolveLock:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.ResolveLock().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(KvResolveLock)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdDeleteRange:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.DeleteRange().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(KvDeleteRange)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdRawGet:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawGet().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(RawGet)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdRawBatchGet:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawBatchGet().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(RawBatchGet)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdRawPut:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawPut().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(RawPut)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdRawBatchPut:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawBatchPut().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(RawBatchPut)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdRawDelete:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawDelete().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(RawDelete)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdRawBatchDelete:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawBatchDelete().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(RawBatchDelete)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdRawDeleteRange:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawDeleteRange().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(RawDeleteRange)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdRawScan:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawScan().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(RawScan)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdGetKeyTTL:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawGetKeyTTL().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(RawGetKeyTTL)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdRawCompareAndSwap:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawCompareAndSwap().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(RawCompareAndSwap)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdRawChecksum:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.RawChecksum().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(RawChecksum)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdCop:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.Cop().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(Coprocessor)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdMvccGetByStartTs:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.MvccGetByStartTs().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(MvccGetByStartTs)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdCheckTxnStatus:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.CheckTxnStatus().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(KvCheckTxnStatus)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdCheckSecondaryLocks:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.CheckSecondaryLocks().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(KvCheckSecondaryLocks)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdTxnHeartBeat:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.TxnHeartBeat().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(KvTxnHeartBeat)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdFlush:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.Flush().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(KvFlush)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdBufferBatchGet:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.BufferBatchGet().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(KvBufferBatchGet)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 case CmdBroadcastTxnStatus:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.BroadcastTxnStatus().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)(BroadcastTxnStatus)
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
 default:
  return nil, errors.Errorf("invalid request type: %v", req.Type)
 }
}

var cmdTypeCanFFI = map[CmdType]struct{}{
 CmdGet: {},
 CmdScan: {},
 CmdPrewrite: {},
 CmdPessimisticLock: {},
 CmdPessimisticRollback: {},
 CmdCommit: {},
 CmdCleanup: {},
 CmdBatchGet: {},
 CmdBatchRollback: {},
 CmdScanLock: {},
 CmdResolveLock: {},
 CmdDeleteRange: {},
 CmdRawGet: {},
 CmdRawBatchGet: {},
 CmdRawPut: {},
 CmdRawBatchPut: {},
 CmdRawDelete: {},
 CmdRawBatchDelete: {},
 CmdRawDeleteRange: {},
 CmdRawScan: {},
 CmdGetKeyTTL: {},
 CmdRawCompareAndSwap: {},
 CmdRawChecksum: {},
 CmdCop: {},
 CmdMvccGetByStartTs: {},
 CmdCheckTxnStatus: {},
 CmdCheckSecondaryLocks: {},
 CmdTxnHeartBeat: {},
 CmdFlush: {},
 CmdBufferBatchGet: {},
 CmdBroadcastTxnStatus: {},
}

func CmdTypeCanFFI(ty CmdType) bool {
 _, ok := cmdTypeCanFFI[ty]
 return ok
}

var cmdTypeFFIWithChannel = map[CmdType]struct{}{
}

func CmdTypeFFIWithChannel(ty CmdType) bool {
 _, ok := cmdTypeFFIWithChannel[ty]
 return ok
}
