// Code generated by go generate; DO NOT EDIT.
//go:build fusion
package tikvrpc

//#include "libtikv.h"
import "C"
import (
 "time"
 "unsafe"

 "github.com/pingcap/errors"
 "github.com/tikv/client-go/v2/internal/logutil"
 "go.uber.org/zap"
)

//export TiKVClientAsyncApiSendResponse
func TiKVClientAsyncApiSendResponse(method C.uint64_t, respDataPtr *C.uchar, respDataLen C.uint64_t, respChPtr C.uintptr_t) {
 switch method {
 case KvGet:
  panic("unreachable now")
 case KvScan:
  panic("unreachable now")
 case KvPrewrite:
  panic("unreachable now")
 case KvPessimisticLock:
  panic("unreachable now")
 case KVPessimisticRollback:
  panic("unreachable now")
 case KvTxnHeartBeat:
  panic("unreachable now")
 case KvCheckTxnStatus:
  panic("unreachable now")
 case KvCheckSecondaryLocks:
  panic("unreachable now")
 case KvCommit:
  panic("unreachable now")
 case KvImport:
  panic("unreachable now")
 case KvCleanup:
  panic("unreachable now")
 case KvBatchGet:
  panic("unreachable now")
 case KvBatchRollback:
  panic("unreachable now")
 case KvScanLock:
  panic("unreachable now")
 case KvResolveLock:
  panic("unreachable now")
 case KvGC:
  panic("unreachable now")
 case KvDeleteRange:
  panic("unreachable now")
 case KvPrepareFlashbackToVersion:
  panic("unreachable now")
 case KvFlashbackToVersion:
  panic("unreachable now")
 case KvFlush:
  panic("unreachable now")
 case KvBufferBatchGet:
  panic("unreachable now")
 case RawGet:
  panic("unreachable now")
 case RawBatchGet:
  panic("unreachable now")
 case RawPut:
  panic("unreachable now")
 case RawBatchPut:
  panic("unreachable now")
 case RawDelete:
  panic("unreachable now")
 case RawBatchDelete:
  panic("unreachable now")
 case RawScan:
  panic("unreachable now")
 case RawDeleteRange:
  panic("unreachable now")
 case RawBatchScan:
  panic("unreachable now")
 case RawGetKeyTTL:
  panic("unreachable now")
 case RawCompareAndSwap:
  panic("unreachable now")
 case RawChecksum:
  panic("unreachable now")
 case UnsafeDestroyRange:
  panic("unreachable now")
 case RegisterLockObserver:
  panic("unreachable now")
 case CheckLockObserver:
  panic("unreachable now")
 case RemoveLockObserver:
  panic("unreachable now")
 case PhysicalScanLock:
  panic("unreachable now")
 case Coprocessor:
  panic("unreachable now")
 case RawCoprocessor:
  panic("unreachable now")
 case SplitRegion:
  panic("unreachable now")
 case ReadIndex:
  panic("unreachable now")
 case MvccGetByKey:
  panic("unreachable now")
 case MvccGetByStartTs:
  panic("unreachable now")
 case CheckLeader:
  panic("unreachable now")
 case GetStoreSafeTS:
  panic("unreachable now")
 case GetLockWaitInfo:
  panic("unreachable now")
 case Compact:
  panic("unreachable now")
 case GetLockWaitHistory:
  panic("unreachable now")
 case GetHealthFeedback:
  panic("unreachable now")
 case BroadcastTxnStatus:
  panic("unreachable now")
 default:
  logutil.BgLogger().Error("Unknown method", zap.Int64("method", int64(method)))
 }
}

//export TiKVClientAsyncApiSendError
func TiKVClientAsyncApiSendError(method C.uint64_t, errEnum C.uint64_t, chPtr C.uintptr_t) {
 errCh := *(*chan respOrErr)(unsafe.Pointer(uintptr(chPtr)))
 errEnum2 := uint64(errEnum)
 err, ok := errEnumMapping[errEnum2]
 if !ok {
  err = errors.Errorf("unknown error: %d", errEnum2)
 }
 errCh <- respOrErr{err: err, ts: time.Now().UnixMicro()}
}
