package main

import (
	"fmt"
	"os"
	"text/template"
)

const tmpl = `// Code generated by go generate; DO NOT EDIT.
//go:build !no_ffi
package tikvrpc

//#include "libtikv.h"
import "C"
import (
 "time"
 "unsafe"

 "github.com/pingcap/errors"
 "github.com/tikv/client-go/v2/internal/logutil"
 "go.uber.org/zap"
)

//export TiKVClientAsyncApiSendResponse
func TiKVClientAsyncApiSendResponse(method C.uint64_t, respDataPtr *C.uchar, respDataLen C.uint64_t, respChPtr C.uintptr_t) {
 switch method {
  {{- range . }}
 case {{ .Method }}:
  {{- if not .UseChan }}
  panic("unreachable now")
  {{- else }}
  respData := unsafe.Slice((*byte)(unsafe.Pointer(respDataPtr)), int(respDataLen))
  {{- if .CopyResp}}
  // Some types of responses are zero copy unmarshal.
  // But the original bytes passed from Rust are on Rust's execution stack and will destroy when the function returns.
  // To avoid dangling pointers, the original bytes need to be copied here.
  // Currently known zero copy structures:
  //   - github.com/pingcap/kvproto/pkg/sharedbytes.SharedBytes
  tmp := make([]byte, len(respData))
  copy(tmp, respData)
  respData = tmp
  {{- end }}
  resp := &{{ .TypePrefix }}Response{}
  err := resp.Unmarshal(respData)
  if err != nil {
   logutil.BgLogger().Error("unmarshal response failed", zap.Error(err), zap.ByteString("resp", respData))
  }
  respCh := *(*chan respOrErr)(unsafe.Pointer(uintptr(respChPtr)))
  respCh <- respOrErr{resp: &Response{Resp: resp}, ts: time.Now().UnixMicro()}
  {{- end }}
  {{- end }}
 default:
  logutil.BgLogger().Error("Unknown method", zap.Int64("method", int64(method)))
 }
}

//export TiKVClientAsyncApiSendError
func TiKVClientAsyncApiSendError(method C.uint64_t, errEnum C.uint64_t, chPtr C.uintptr_t) {
 errCh := *(*chan respOrErr)(unsafe.Pointer(uintptr(chPtr)))
 errEnum2 := uint64(errEnum)
 err, ok := errEnumMapping[errEnum2]
 if !ok {
  err = errors.Errorf("unknown error: %d", errEnum2)
 }
 errCh <- respOrErr{err: err, ts: time.Now().UnixMicro()}
}
`

func main() {
	f, err := os.Create("send_response_gen.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	t := template.Must(template.New("sendResponse").Parse(tmpl))
	err = t.Execute(f, mappings)
	if err != nil {
		panic(err)
	}

	fmt.Println("send_response_gen.go generated successfully.")
}
