package main

import (
	"fmt"
	"os"
	"text/template"
)

const tmpl2 = `// Code generated by go generate; DO NOT EDIT.
//go:build !no_ffi
package tikvrpc

//#include "libtikv.h"
{{- if allUseChanFalse .Method2Mappings }}
//#cgo nocallback tikv_client_async_api_send_request
{{- end }}
//#cgo nocallback tikv_client_drop_response
import "C"
import (
 "context"
 "encoding/binary"
 "fmt"
 "math"
 "runtime"
 "time"
 "unsafe"

 "github.com/pingcap/errors"
 "github.com/tikv/client-go/v2/metrics"
 "github.com/pingcap/kvproto/pkg/kvrpcpb"
 "github.com/pingcap/kvproto/pkg/coprocessor"
)

type respOrErr struct {
 resp *Response
 err  error
 ts   int64 // ts record the timestamp when notify
}

func CallFFIWithEventFD(ctx context.Context, req *Request) (*Response, error) {
 observer := metrics.TiKVFFIMicroSecHistogramVec.WithLabelValues(req.Type.String())
 now := time.Now()
 defer func() {
     observer.Observe(float64(time.Since(now).Microseconds()))
 }()
 switch req.Type {
  {{- range .Mappings2 }}
 case {{ .Cmd }}:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.{{ .Member }}().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  f, fd, err := GetEventFDFile()
  if err != nil {
   f, fd, err = CreateEventFDFile()
   if err != nil {
    return nil, errors.WithStack(err)
   }
  }
  defer PutEventFDFile(f, fd)
  m := (C.uint64_t)({{ .Method }})
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  var respOut *C.uchar
  var respLen C.uint64_t
  var respCap C.uint64_t
  var ts C.uint64_t
  eventFd := (C.int)(fd)
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   (*C.uchar)(nil),
   &respOut,
   &respLen,
   &respCap,
   &ts,
   eventFd,
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  defer func() {
   if respLen != 0 && respCap != 0 {
    // we assume the corresponding resp has already been set in respOut
    C.tikv_client_drop_response(respOut, respLen, respCap)
   }
  }()
  ty := waitEventFDFile(f)
  respBytes := unsafe.Slice((*byte)(respOut), uint64(respLen))
  if ts != math.MaxUint64 {
   waitObserver.Observe(float64(uint64(time.Now().UnixMicro()) - uint64(ts)))
  }
  {{- if (index $.Method2Mappings .Method).CopyResp }}
  // Some types of responses are zero copy unmarshal.
  // But the original bytes passed from Rust are on Rust's execution stack and will destroy when the function returns.
  // To avoid dangling pointers, the original bytes need to be copied here.
  // Currently known zero copy structures:
  //   - github.com/pingcap/kvproto/pkg/sharedbytes.SharedBytes
  tmp := make([]byte, uint64(respLen))
  copy(tmp, respBytes)
  respBytes = tmp
  {{- end }}
  defer func() {
   runtime.KeepAlive(&reqBytes)
   runtime.KeepAlive(&respOut)
   runtime.KeepAlive(&respLen)
   runtime.KeepAlive(&respCap)
   runtime.KeepAlive(&ts)
  }()
  if ty == uint64(C.FD_SUCCESS_CODE) {
   resp := &{{ (index $.Method2Mappings .Method).TypePrefix }}Response{}
   if err := resp.Unmarshal(respBytes); err != nil {
    return nil, err
   }
   return &Response{Resp: resp}, nil
  } else if ty == uint64(C.FD_SUCCESS_CODE) {
   if respLen != 8 {
    return nil, errors.New("unknown error")
   } else {
    errEnum := binary.LittleEndian.Uint64(respBytes)
    err, ok := errEnumMapping[errEnum]
    if !ok {
     err = errors.Errorf("unknown error: %d", errEnum)
    }
    return nil, err
   }
  } else {
	panic(fmt.Sprintf("unknown response type %d", ty))
  }
  {{- end }}
 default:
  return nil, errors.Errorf("invalid request type: %v", req.Type)
 }
}

func CallFFIWithChannel(ctx context.Context, req *Request) (*Response, error) {
 observer := metrics.TiKVFFIMicroSecHistogramVec.WithLabelValues(req.Type.String())
 now := time.Now()
 defer func() {
     observer.Observe(float64(time.Since(now).Microseconds()))
 }()
 ch := make(chan respOrErr, 1)
 chPtr := (*C.uchar)(unsafe.Pointer(&ch))
 switch req.Type {
  {{- range .Mappings2 }}
 case {{ .Cmd }}:
  callObserver := metrics.TiKVFFICallMicroSecHistogramVec.WithLabelValues(req.Type.String())
  reqBytes, err := req.{{ .Member }}().Marshal()
  if err != nil {
   return nil, errors.WithStack(err)
  }
  m := (C.uint64_t)({{ .Method }})
  reqPtr := (*C.uchar)(unsafe.Pointer(&reqBytes[0]))
  reqLen := (C.uint64_t)(len(reqBytes))
  C.tikv_client_async_api_send_request(
   m,
   reqPtr,
   reqLen,
   chPtr,
   (**C.uchar)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (*C.uint64_t)(nil),
   (C.int)(-1),
  )
  callObserver.Observe(float64(time.Since(now).Microseconds()))
  waitObserver := metrics.TiKVFFIWaitMicroSecHistogramVec.WithLabelValues(req.Type.String())
  ffiResult := <-ch
  waitObserver.Observe(float64(time.Now().UnixMicro() - ffiResult.ts))
  runtime.KeepAlive(&ch)
  runtime.KeepAlive(&reqBytes)
  return ffiResult.resp, ffiResult.err
  {{- end }}
 default:
  return nil, errors.Errorf("invalid request type: %v", req.Type)
 }
}

var cmdTypeCanFFI = map[CmdType]struct{}{
 {{- range .Mappings2 }}
 {{ .Cmd }}: {},
 {{- end }}
}

func CmdTypeCanFFI(ty CmdType) bool {
 _, ok := cmdTypeCanFFI[ty]
 return ok
}

var cmdTypeFFIWithChannel = map[CmdType]struct{}{
 {{- range .Mappings2 }}
  {{- if (index $.Method2Mappings .Method).UseChan }}
   {{ .Cmd }}: {},
  {{- end }}
 {{- end }}
}

func CmdTypeFFIWithChannel(ty CmdType) bool {
 _, ok := cmdTypeFFIWithChannel[ty]
 return ok
}
`

var mappings2 = []struct {
	Cmd    string
	Member string
	Method string
}{
	{"CmdGet", "Get", "KvGet"},
	{"CmdScan", "Scan", "KvScan"},
	{"CmdPrewrite", "Prewrite", "KvPrewrite"},
	{"CmdPessimisticLock", "PessimisticLock", "KvPessimisticLock"},
	{"CmdPessimisticRollback", "PessimisticRollback", "KVPessimisticRollback"},
	{"CmdCommit", "Commit", "KvCommit"},
	{"CmdCleanup", "Cleanup", "KvCleanup"},
	{"CmdBatchGet", "BatchGet", "KvBatchGet"},
	{"CmdBatchRollback", "BatchRollback", "KvBatchRollback"},
	{"CmdScanLock", "ScanLock", "KvScanLock"},
	{"CmdResolveLock", "ResolveLock", "KvResolveLock"},
	{"CmdDeleteRange", "DeleteRange", "KvDeleteRange"},
	{"CmdRawGet", "RawGet", "RawGet"},
	{"CmdRawBatchGet", "RawBatchGet", "RawBatchGet"},
	{"CmdRawPut", "RawPut", "RawPut"},
	{"CmdRawBatchPut", "RawBatchPut", "RawBatchPut"},
	{"CmdRawDelete", "RawDelete", "RawDelete"},
	{"CmdRawBatchDelete", "RawBatchDelete", "RawBatchDelete"},
	{"CmdRawDeleteRange", "RawDeleteRange", "RawDeleteRange"},
	{"CmdRawScan", "RawScan", "RawScan"},
	{"CmdGetKeyTTL", "RawGetKeyTTL", "RawGetKeyTTL"},
	{"CmdRawCompareAndSwap", "RawCompareAndSwap", "RawCompareAndSwap"},
	{"CmdRawChecksum", "RawChecksum", "RawChecksum"},
	{"CmdCop", "Cop", "Coprocessor"},
	{"CmdMvccGetByStartTs", "MvccGetByStartTs", "MvccGetByStartTs"},
	{"CmdCheckTxnStatus", "CheckTxnStatus", "KvCheckTxnStatus"},
	{"CmdCheckSecondaryLocks", "CheckSecondaryLocks", "KvCheckSecondaryLocks"},
	{"CmdTxnHeartBeat", "TxnHeartBeat", "KvTxnHeartBeat"},
	{"CmdFlush", "Flush", "KvFlush"},
	{"CmdBufferBatchGet", "BufferBatchGet", "KvBufferBatchGet"},
	{"CmdBroadcastTxnStatus", "BroadcastTxnStatus", "BroadcastTxnStatus"},
}

type globalVarAccessor struct {
	Method2Mappings map[string]struct {
		TypePrefix string
		CopyResp   bool
		UseChan    bool
	}
	Mappings2 []struct {
		Cmd    string
		Member string
		Method string
	}
}

func allUseChanFalse(m map[string]struct {
	TypePrefix string
	CopyResp   bool
	UseChan    bool
}) bool {
	for _, v := range m {
		if v.UseChan {
			return false
		}
	}
	return true
}

func main() {
	f, err := os.Create("call_ffi_gen.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	t := template.Must(template.
		New("callFFI").
		Funcs(template.FuncMap{"allUseChanFalse": allUseChanFalse}).
		Parse(tmpl2))
	err = t.Execute(f, globalVarAccessor{
		Method2Mappings: method2Mappings,
		Mappings2:       mappings2,
	})
	if err != nil {
		panic(err)
	}

	fmt.Println("call_ffi_gen.go generated successfully.")
}
